name: Build and Publish to Dockerhub
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build --file /docker-android-emulator/Dockerfile 
       
